linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - errcheck
    - typecheck
    - unused
    - bodyclose
    - exportloopref
    - gocritic
    - goprintffuncname
    - gosec
    - nilerr
    - revive
    - stylecheck
  disable:
    - golint

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - test_videos/
  skip-files:
    - ".*\\.generated\\.go$"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    - linters:
        - lll
      source: "http(s)?://"
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  lll:
    line-length: 120
  gosec:
    excludes:
      - G104
  govet:
    check-shadowing: true
  unused:
    check-exported: false
