linters:
  enable:
    - gofmt
    - govet
    - golint
    - gosimple
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - goimports

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - test_videos/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
