name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment for manual trigger'
        required: false
        default: 'Manual integration test run'

jobs:
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: go mod download
        
      - name: Build VidKit
        run: go build -o vidkit ./cmd/vidkit
        
      - name: Generate test videos
        run: |
          echo "Generating test videos using tools/generate_test_videos.sh..."
          chmod +x ./tools/generate_test_videos.sh
          ./tools/generate_test_videos.sh
          echo "Number of test videos generated: $(ls -l test_videos/*.mp4 | wc -l)"

      - name: Run CI integration tests
        run: make ci-integration-test

      - name: Test directory organization features
        run: make test-organization-ci
          
      - name: Test resolution detection
        run: make test-resolution-ci
          
      - name: Test error handling
        run: make test-error-handling-ci
          
      - name: Test CLI functionality
        run: make test-cli-ci
      
      - name: Archive test files on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs
          path: |
            output.log
            test_videos/
            test_organization/
            test_results/
